name: Build and deploy Node.js app to Azure Web App - vic-sports-api

on:
  push:
    branches:
      - main
      - develop  # Thêm develop branch vì bạn đang work trên branch này
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # Sử dụng Node 20.x để tương thích tốt hơn

      - name: Validate package.json
        run: |
          cat package.json
          node -e "require('./package.json')"

      - name: npm install and test
        run: |
          npm install
          npm run test --if-present

      - name: Create deployment package
        run: |
          # Copy necessary files for deployment
          mkdir deploy-package
          cp -r src deploy-package/
          cp package.json deploy-package/
          cp package-lock.json deploy-package/ || echo "No package-lock.json found"
          
          # Create zip file
          cd deploy-package
          zip -r ../release.zip . -x "*.git*" -x "*.github*" -x "logs/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production  # Thêm environment để quản lý secrets tốt hơn
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: .
        env:
          # Environment variables cho ứng dụng
          NODE_ENV: production
          PORT: 8080
