# Tên của workflow, sẽ hiển thị trong tab "Actions" trên GitHub
name: Deploy Vic Sports Frontend to Vercel

# Điều kiện để kích hoạt workflow: chạy khi có push lên nhánh develop hoặc main
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Bước 1: Lấy mã nguồn về máy ảo
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Bước 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install
          npm audit fix --force

      # Bước 4: Build project
      - name: Build project
        run: vite build
        env:
          NODE_ENV: production

      # Bước 5: Đồng bộ các biến môi trường từ GitHub Secrets sang Vercel (nếu cần)
      - name: Sync Environment Variables to Vercel
        if: ${{ vars.SYNC_ENV_VARS == 'true' }}
        uses: dkershner6/vercel-set-env-action@v1
        with:
          # Token để xác thực với Vercel
          token: ${{ secrets.VERCEL_TOKEN }}

          # !!! QUAN TRỌNG: Thay thế bằng tên dự án chính xác của bạn trên Vercel
          projectName: "vic-sports-frontend" # Tên project Vic Sports

          # Liệt kê các environment variables cho Vic Sports project
          envVariableKeys: VITE_BACKEND_URL,VITE_GOOGLE_MAPS_API_KEY,VITE_GOOGLE_CLIENT_ID,CLIENT_EMAIL,PRIVATE_KEY,SPREADSHEET_ID
        env:
          # --- Cấu hình cho Backend URL (API + Socket.IO) ---
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
          TARGET_VITE_BACKEND_URL: production
          TYPE_VITE_BACKEND_URL: encrypted

          # --- Cấu hình cho Google Maps API Key ---
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
          TARGET_VITE_GOOGLE_MAPS_API_KEY: production
          TYPE_VITE_GOOGLE_MAPS_API_KEY: encrypted

          # --- Cấu hình cho Google OAuth Client ID ---
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          TARGET_VITE_GOOGLE_CLIENT_ID: production
          TYPE_VITE_GOOGLE_CLIENT_ID: encrypted

          # --- Cấu hình cho Google Sheets Service Account ---
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          TARGET_CLIENT_EMAIL: production
          TYPE_CLIENT_EMAIL: encrypted

          # --- Cấu hình cho Google Sheets Private Key ---
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          TARGET_PRIVATE_KEY: production
          TYPE_PRIVATE_KEY: encrypted

          # --- Cấu hình cho Spreadsheet ID ---
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          TARGET_SPREADSHEET_ID: production
          TYPE_SPREADSHEET_ID: encrypted

      # Bước 6: Deploy dự án lên Vercel
      - name: Deploy Project to Vercel
        uses: amondnet/vercel-action@v25
        with:
          # Token Vercel để xác thực
          vercel-token: ${{ secrets.VERCEL_TOKEN }}

          # Token GitHub để Vercel liên kết commit (có sẵn, không cần tạo)
          github-token: ${{ secrets.GITHUB_TOKEN }}

          # Argument để báo cho Vercel đây là bản deploy production
          vercel-args: "--prod"

          # ID của tài khoản Vercel (cá nhân hoặc team)
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}

          # ID của dự án trên Vercel
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}

          # Thư mục gốc vì project nằm ở root
          working-directory: ./
